### ISSUE TITLE
Add inbostats tutorials

### ISSUE THREAD

**Issue by hansvancalster** [inbo/tutorials#142]
Add relevant tutorials from the [inbostats rpubs page](http://rpubs.com/INBOstats) to the tutorials website

Review & merge needed of following pull requests:

- [X] Add rpubs tutorial on paired t-test #172
- [X] Add rpubs tutorial same fixed and random effect #173
- [ ] Add rpubs about lexical scoping #174
- [ ] Add olre rpubs tutorial #175
- [ ] add wip tutorial on correlated random effects #176
- [ ] Add rpubs tutorial zero-inflation #177
- [ ] Add rpubs tutorial on zooming in with ggplot2 #178
- [ ] Add rpubs spde tutorial #179
- [X] Patches rpubs #180

**Comment by florisvdh** [comment]
Reopening issue because 6 pull requests await review.

@ThierryO I assigned you to this issue because @hansvancalster asked you to review these PRs. In order to keep track, a task list has been added at the top of this issue.
